"""GENERATED by scripts/gen_design_tokens.py from docs/DESIGN_SYSTEM.md; do not edit."""

from __future__ import annotations

from typing import Any

DESIGN_SYSTEM_VERSION = 1
TOKENS: dict[str, Any] = {
    "design_system_version": 1,
    "color": {
        "ui": [
            {"id": "ui.surface.0", "oklch": [0.18, 0.01, 260], "role": "canvas"},
            {"id": "ui.surface.1", "oklch": [0.22, 0.012, 260], "role": "panel"},
            {"id": "ui.surface.2", "oklch": [0.26, 0.014, 260], "role": "raised"},
            {"id": "ui.ink.primary", "oklch": [0.96, 0.01, 80], "role": "read text"},
            {"id": "ui.ink.secondary", "oklch": [0.82, 0.012, 80], "role": "labels"},
            {"id": "ui.ink.muted", "oklch": [0.64, 0.012, 80], "role": "axes, captions"},
            {"id": "ui.stroke.soft", "oklch": [0.34, 0.012, 260]},
            {"id": "ui.stroke.strong", "oklch": [0.48, 0.012, 260]},
        ],
        "data": {
            "categorical": [
                {"id": "data.cat.blue", "oklch": [0.532, 0.131, 244.0], "srgb_origin": "#0072B2"},
                {"id": "data.cat.orange", "oklch": [0.753, 0.158, 76.8], "srgb_origin": "#E69F00"},
                {"id": "data.cat.green", "oklch": [0.62, 0.13, 165.5], "srgb_origin": "#009E73"},
                {"id": "data.cat.purple", "oklch": [0.679, 0.118, 346.3], "srgb_origin": "#CC79A7"},
                {
                    "id": "data.cat.vermillion",
                    "oklch": [0.621, 0.17, 47.5],
                    "srgb_origin": "#D55E00",
                },
                {"id": "data.cat.sky", "oklch": [0.735, 0.117, 236.2], "srgb_origin": "#56B4E9"},
            ],
            "sequential": [
                {"t": 0.0, "oklch": [0.252, 0.09, 257.1], "srgb_origin": "#00204C"},
                {"t": 0.125, "oklch": [0.331, 0.116, 256.6], "srgb_origin": "#00336F"},
                {"t": 0.25, "oklch": [0.405, 0.062, 266.0], "srgb_origin": "#39486B"},
                {"t": 0.375, "oklch": [0.477, 0.028, 272.4], "srgb_origin": "#575C6D"},
                {"t": 0.5, "oklch": [0.548, 0.003, 264.5], "srgb_origin": "#707173"},
                {"t": 0.625, "oklch": [0.622, 0.021, 97.0], "srgb_origin": "#8A8779"},
                {"t": 0.75, "oklch": [0.693, 0.056, 96.9], "srgb_origin": "#A69D75"},
                {"t": 0.875, "oklch": [0.77, 0.095, 98.0], "srgb_origin": "#C4B56C"},
                {"t": 1.0, "oklch": [0.927, 0.174, 101.8], "srgb_origin": "#FFEA46"},
            ],
            "diverging": [
                {"t": 0.0, "oklch": [0.45, 0.13, 244]},
                {"t": 0.5, "oklch": [0.72, 0.005, 260]},
                {"t": 1.0, "oklch": [0.75, 0.15, 77]},
            ],
        },
        "state": [
            {
                "id": "state.emphasis",
                "oklch": [0.84, 0.15, 78],
                "role": "the one thing being talked about",
            },
            {
                "id": "state.deemphasis",
                "alpha": 0.35,
                "role": "everything else while emphasis is active",
            },
            {
                "id": "state.uncertain",
                "oklch": [0.72, 0.05, 80],
                "pattern": "hatch",
                "role": "estimated or forecast values",
            },
            {
                "id": "state.quote_highlight",
                "rule": "contrast",
                "role": "source-quote overlay, see Quote highlight",
            },
            {"id": "state.error", "oklch": [0.65, 0.18, 25], "role": "failure states only"},
        ],
    },
    "typography": {
        "faces": {"display": "Sora", "text": "Inter"},
        "scale_px_at_1080": {
            "display": 72,
            "h1": 56,
            "h2": 40,
            "body": 34,
            "label": 28,
            "caption": 26,
        },
        "floors_px_at_1080": {"read_text": 34, "label": 26},
        "line_height": 1.25,
        "max_lines": {"body": 4, "label": 2},
    },
    "layout": {
        "canvas": {"width": 1920, "height": 1080, "fps": 30},
        "safe_area_px": {"x": 96, "y": 54},
        "grid": {"columns": 12, "gutter": 24, "unit": 8},
        "label_distance_max_px": 48,
    },
    "lines": {
        "data_stroke_px": 4,
        "data_stroke_min_px_at_360": 3,
        "axis_stroke_px": 2,
        "grid_stroke_px": 1,
    },
    "motion": {
        "easing": {"standard": [0.2, 0.0, 0.0, 1.0], "move": [0.4, 0.0, 0.2, 1.0]},
        "duration_ms": {
            "reveal": 400,
            "hide": 250,
            "highlight": 200,
            "move_short": 600,
            "move_long": 1200,
            "zoom": 900,
        },
        "rules": [
            "no overshoot or spring on data values",
            "one camera move at a time; zoom factor at most 2.5",
            "a value change is a linear interpolation with the standard easing, or a hard cut",
            "hold at least the reading-time floor before the next action on the same target",
        ],
    },
}
SRGB_HEX: dict[str, str] = {
    "data.cat.blue": "#0172B2",
    "data.cat.green": "#009E73",
    "data.cat.orange": "#E69F00",
    "data.cat.purple": "#CC79A7",
    "data.cat.sky": "#57B4E9",
    "data.cat.vermillion": "#D55E01",
    "data.diverging[0]": "#005A8E",
    "data.diverging[1]": "#A3A5A8",
    "data.diverging[2]": "#E29F1E",
    "data.sequential[0]": "#00204C",
    "data.sequential[1]": "#00336F",
    "data.sequential[2]": "#39486B",
    "data.sequential[3]": "#575C6D",
    "data.sequential[4]": "#707173",
    "data.sequential[5]": "#8A8779",
    "data.sequential[6]": "#A69D75",
    "data.sequential[7]": "#C4B56C",
    "data.sequential[8]": "#FFEA46",
    "state.emphasis": "#FFBD4A",
    "state.error": "#E85854",
    "state.uncertain": "#B5A282",
    "ui.ink.muted": "#908B84",
    "ui.ink.primary": "#F5F1EA",
    "ui.ink.secondary": "#C8C3BC",
    "ui.stroke.soft": "#34383E",
    "ui.stroke.strong": "#5A5E65",
    "ui.surface.0": "#0F1216",
    "ui.surface.1": "#171B20",
    "ui.surface.2": "#20242B",
}
