"""phase12 engagement inbox

Revision ID: ea1f9e65b372
Revises: 6d7fb293d02e
Create Date: 2026-09-01 16:33:10.525381
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ea1f9e65b372"
down_revision: str | None = "6d7fb293d02e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagement_messages",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("account_handle", sa.String(length=200), nullable=False),
        sa.Column("message_id", sa.String(length=200), nullable=False),
        sa.Column("thread_id", sa.String(length=200), nullable=False),
        sa.Column("fan_id", sa.String(length=200), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.String(length=64), nullable=False),
        sa.Column("message_class", sa.String(length=40), nullable=False),
        sa.Column("vip", sa.Boolean(), nullable=False),
        sa.Column(
            "disposition",
            sa.Enum("pending", "answered", "skipped", name="message_disposition"),
            nullable=False,
        ),
        sa.Column("skip_reason", sa.String(length=300), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_engagement_messages_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_engagement_messages")),
        sa.UniqueConstraint(
            "workspace_id",
            "platform",
            "message_id",
            name=op.f("uq_engagement_messages_workspace_id"),
        ),
    )
    op.create_index(
        op.f("ix_engagement_messages_workspace_id"),
        "engagement_messages",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_engagement_messages_workspace_id"), table_name="engagement_messages")
    op.drop_table("engagement_messages")
    # ### end Alembic commands ###
