"""phase6 runs nodes action items

Revision ID: a9fda06f23f1
Revises: 7a678303d19a
Create Date: 2026-09-01 07:17:21.686273
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a9fda06f23f1"
down_revision: str | None = "7a678303d19a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_items",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.Enum("open", "resolved", name="action_item_status"), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("deep_link", sa.String(length=300), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_action_items_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_items")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_action_items_dedupe_key")),
    )
    op.create_index(op.f("ix_action_items_run_id"), "action_items", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_action_items_workspace_id"), "action_items", ["workspace_id"], unique=False
    )
    op.create_table(
        "production_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "created",
                "preflighting",
                "waiting_for_approval",
                "approved",
                "producing",
                "complete",
                "blocked",
                "failed",
                "cancelled",
                name="run_state",
            ),
            nullable=False,
        ),
        sa.Column("quality", sa.String(length=20), nullable=False),
        sa.Column("preflight_revision_hash", sa.String(length=64), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_production_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_runs")),
    )
    op.create_index(
        op.f("ix_production_runs_workspace_id"), "production_runs", ["workspace_id"], unique=False
    )
    op.create_table(
        "run_nodes",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("node_id", sa.String(length=120), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("deliverable_id", sa.String(length=40), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "queued", "running", "complete", "failed", "blocked", "skipped", name="node_state"
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["production_runs.id"],
            name=op.f("fk_run_nodes_run_id_production_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_run_nodes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_nodes")),
        sa.UniqueConstraint("run_id", "node_id", name=op.f("uq_run_nodes_run_id")),
    )
    op.create_index(op.f("ix_run_nodes_run_id"), "run_nodes", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_nodes_workspace_id"), "run_nodes", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_nodes_workspace_id"), table_name="run_nodes")
    op.drop_index(op.f("ix_run_nodes_run_id"), table_name="run_nodes")
    op.drop_table("run_nodes")
    op.drop_index(op.f("ix_production_runs_workspace_id"), table_name="production_runs")
    op.drop_table("production_runs")
    op.drop_index(op.f("ix_action_items_workspace_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_run_id"), table_name="action_items")
    op.drop_table("action_items")
    # ### end Alembic commands ###
