"""phase12 personas brand_nodes portal

Revision ID: 6d7fb293d02e
Revises: 03c491d8363a
Create Date: 2026-09-01 16:18:26.997076
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d7fb293d02e"
down_revision: str | None = "03c491d8363a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brand_nodes",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("parent_id", sa.String(length=40), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("tokens", sa.JSON(), nullable=False),
        sa.Column("locked_tokens", sa.JSON(), nullable=False),
        sa.Column("policies", sa.JSON(), nullable=False),
        sa.Column("locked_policies", sa.JSON(), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["brand_nodes.id"],
            name=op.f("fk_brand_nodes_parent_id_brand_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_brand_nodes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_nodes")),
    )
    op.create_index(
        op.f("ix_brand_nodes_workspace_id"), "brand_nodes", ["workspace_id"], unique=False
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_personas_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personas")),
    )
    op.create_index(op.f("ix_personas_workspace_id"), "personas", ["workspace_id"], unique=False)
    op.create_table(
        "portal_links",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("token_sha256", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_portal_links_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portal_links")),
        sa.UniqueConstraint("token_sha256", name=op.f("uq_portal_links_token_sha256")),
    )
    op.create_index(
        op.f("ix_portal_links_workspace_id"), "portal_links", ["workspace_id"], unique=False
    )
    op.create_table(
        "portal_briefs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("link_id", sa.String(length=40), nullable=False),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("deadline", sa.String(length=100), nullable=True),
        sa.Column("contact", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "accepted", "declined", name="portal_brief_status"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.String(length=64), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["portal_links.id"],
            name=op.f("fk_portal_briefs_link_id_portal_links"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_portal_briefs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portal_briefs")),
    )
    op.create_index(
        op.f("ix_portal_briefs_workspace_id"), "portal_briefs", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_portal_briefs_workspace_id"), table_name="portal_briefs")
    op.drop_table("portal_briefs")
    op.drop_index(op.f("ix_portal_links_workspace_id"), table_name="portal_links")
    op.drop_table("portal_links")
    op.drop_index(op.f("ix_personas_workspace_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_brand_nodes_workspace_id"), table_name="brand_nodes")
    op.drop_table("brand_nodes")
    # ### end Alembic commands ###
