"""phase9 connections distribution

Revision ID: 03c491d8363a
Revises: 7f5423884b80
Create Date: 2026-09-01 08:34:03.282609
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "03c491d8363a"
down_revision: str | None = "7f5423884b80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connected_accounts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("handle", sa.String(length=200), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("token_key_id", sa.String(length=24), nullable=False),
        sa.Column("token_nonce", sa.String(length=64), nullable=False),
        sa.Column("token_ciphertext", sa.Text(), nullable=False),
        sa.Column("refresh_key_id", sa.String(length=24), nullable=True),
        sa.Column("refresh_nonce", sa.String(length=64), nullable=True),
        sa.Column("refresh_ciphertext", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health", sa.String(length=20), nullable=False),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_connected_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connected_accounts")),
        sa.UniqueConstraint(
            "workspace_id", "platform", "handle", name=op.f("uq_connected_accounts_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_connected_accounts_workspace_id"),
        "connected_accounts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "distribution_profiles",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("authorized_by", sa.String(length=64), nullable=True),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_distribution_profiles_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distribution_profiles")),
        sa.UniqueConstraint(
            "workspace_id", "name", "revision", name=op.f("uq_distribution_profiles_workspace_id")
        ),
    )
    op.create_index(
        op.f("ix_distribution_profiles_workspace_id"),
        "distribution_profiles",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "distribution_state",
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.Column("kill_switch", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_distribution_state_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_distribution_state")),
    )
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("code_verifier", sa.String(length=256), nullable=False),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("workspace_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_oauth_states_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_states")),
        sa.UniqueConstraint("state", name=op.f("uq_oauth_states_state")),
    )
    op.create_index(
        op.f("ix_oauth_states_workspace_id"), "oauth_states", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_oauth_states_workspace_id"), table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_table("distribution_state")
    op.drop_index(op.f("ix_distribution_profiles_workspace_id"), table_name="distribution_profiles")
    op.drop_table("distribution_profiles")
    op.drop_index(op.f("ix_connected_accounts_workspace_id"), table_name="connected_accounts")
    op.drop_table("connected_accounts")
    # ### end Alembic commands ###
