"""perf composite indexes

Revision ID: 8c5a9db8e9e5
Revises: ea1f9e65b372
Create Date: 2026-09-01 16:41:01.229038
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "8c5a9db8e9e5"
down_revision: str | None = "ea1f9e65b372"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_action_items_ws_status", "action_items", ["workspace_id", "status"], unique=False
    )
    op.create_index(
        "ix_engagement_messages_ws_disposition",
        "engagement_messages",
        ["workspace_id", "disposition"],
        unique=False,
    )
    op.create_index(
        "ix_production_runs_ws_created",
        "production_runs",
        ["workspace_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_production_runs_ws_created", table_name="production_runs")
    op.drop_index("ix_engagement_messages_ws_disposition", table_name="engagement_messages")
    op.drop_index("ix_action_items_ws_status", table_name="action_items")
    # ### end Alembic commands ###
