/**
 * Dump the workspace node catalogue to JSON so Python can validate workflow definitions.
 *
 *   node scripts/dump_node_catalog.mjs
 *
 * Writes fixtures/schema/node_catalog.json: per node type, its declared widget names, input slots
 * and output slots. The definitions in workflows/*.yaml are checked against it, which is what turns
 * a typo'd widget key from a silently ignored value into a failed validation.
 *
 * The catalogue is TypeScript with workspace imports, so it is bundled with esbuild (already a
 * dependency of the web app) and imported. Reading it with a regex would be guessing.
 */

import { createRequire } from "node:module";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(REPO, "apps/web/src/workspace/catalog.ts");
const OUT = join(REPO, "fixtures/schema/node_catalog.json");

// esbuild is a transitive dependency under pnpm's store rather than a root one, so it is resolved
// from the store path instead of by bare name. glob the version so an upgrade does not break this.
const { readdirSync } = await import("node:fs");
const store = join(REPO, "node_modules/.pnpm");
const esbuildDir = readdirSync(store)
  .filter((d) => d.startsWith("esbuild@"))
  .sort()
  .at(-1);
if (!esbuildDir) {
  throw new Error(`esbuild not found under ${store}; run pnpm install`);
}
const require_ = createRequire(join(store, esbuildDir, "node_modules/esbuild/package.json"));
const { build } = require_("esbuild");

const dir = await mkdtemp(join(tmpdir(), "cf-catalog-"));
const bundle = join(dir, "catalog.mjs");
try {
  await build({
    entryPoints: [ENTRY],
    outfile: bundle,
    bundle: true,
    format: "esm",
    platform: "node",
    logLevel: "silent",
    // The catalogue only needs the type-level Stage import and createCatalog; resolve the
    // workspace packages from their sources so no build step is required first.
    alias: {
      "@content-factory/node-graph": join(REPO, "packages/node-graph/src/index.ts"),
      "@content-factory/content-schema-ts": join(
        REPO,
        "packages/content-schema-ts/src/index.ts",
      ),
    },
  });

  const mod = await import(bundle);
  const catalog = mod.WORKSPACE_DEFS ?? mod.NODE_CATALOG ?? mod.default;
  if (!catalog) {
    throw new Error("catalog.ts exported no WORKSPACE_DEFS");
  }
  const defs = Array.isArray(catalog) ? catalog : Object.values(catalog);

  const out = {};
  for (const def of defs) {
    const type = def.type ?? def.stage;
    if (!type) continue;
    out[type] = {
      title: def.title ?? "",
      category: def.category ?? "",
      executor: def.executor ?? null,
      widgets: (def.widgets ?? []).map((w) => w.name),
      // Declared option lists, so a definition cannot set a combo to a value the widget refuses.
      // A widget with no options (text, number, seed, boolean) is absent from this map.
      widget_options: Object.fromEntries(
        (def.widgets ?? [])
          .filter((w) => Array.isArray(w.options) && w.options.length > 0)
          .map((w) => [w.name, w.options]),
      ),
      inputs: (def.inputs ?? []).map((s) => s.name),
      outputs: (def.outputs ?? []).map((s) => s.name),
      required_inputs: (def.inputs ?? []).filter((s) => !s.optional).map((s) => s.name),
      // Slot types, so a workflow definition can be checked for a wire the canvas would reject.
      input_types: Object.fromEntries((def.inputs ?? []).map((s) => [s.name, s.type])),
      output_types: Object.fromEntries((def.outputs ?? []).map((s) => [s.name, s.type])),
    };
  }

  const sorted = Object.fromEntries(Object.keys(out).sort().map((k) => [k, out[k]]));
  const doc = {
    $comment:
      "GENERATED by scripts/dump_node_catalog.mjs from apps/web/src/workspace/catalog.ts. " +
      "Do not edit. Regenerate with `just schemas`. Tracked on purpose: it is what lets a " +
      "Python test reject a workflow definition that sets a widget the node does not declare.",
    node_types: sorted,
  };
  await writeFile(OUT, JSON.stringify(doc, null, 1) + "\n");
  console.log(JSON.stringify({ node_types: Object.keys(sorted).length, out: OUT }));
} finally {
  await rm(dir, { recursive: true, force: true });
}
