"""Generate the canvas's workflow data from the definitions in ``workflows/*.yaml``.

    uv run python scripts/export_workflows.py [--check]

Writes two files:

* ``fixtures/schema/workflow_templates.json`` - tracked, canonical JSON. This is the drift gate:
  ``--check`` fails when it is stale, and it is tracked precisely because
  ``packages/content-schema-ts/generated`` and ``apps/web/src/workspace/generated`` are git-ignored,
  so a ``git diff`` gate on the generated TS would always pass and prove nothing.
* ``apps/web/src/workspace/generated/workflowTemplates.ts`` - what the canvas imports.

Nodes without an explicit position are laid out by topological depth, so a definition can leave
positions out and still open as a readable graph.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "python"))

from content_factory.models.weights import (  # noqa: E402
    package_for_requirement,
    skill_env_by_key,
)
from content_factory.schemas.base import canonical_dumps  # noqa: E402
from content_factory.workflows.catalog import (  # noqa: E402
    _layout_depth,
    _row_within_depth,
    load_definitions,
    runnable_missing_executor,
)

JSON_OUT = REPO_ROOT / "fixtures" / "schema" / "workflow_templates.json"
TS_OUT = REPO_ROOT / "apps" / "web" / "src" / "workspace" / "generated" / "workflowTemplates.ts"

BANNER = (
    "// GENERATED by scripts/export_workflows.py from workflows/*.yaml. Do not edit.\n"
    "// Add or change a workflow by editing its YAML file and running `just schemas`.\n"
)


def positioned(template) -> list[dict]:
    """Every node with a definite x and y, so the canvas never has to invent one."""
    depth = _layout_depth(template)
    out = []
    for node in template.nodes:
        x = node.x if node.x is not None else -1280.0 + 340.0 * depth[node.key]
        y = node.y if node.y is not None else 130.0 * _row_within_depth(template, node.key, depth)
        entry = {
            "key": node.key,
            "type": node.type,
            "x": round(float(x), 1),
            "y": round(float(y), 1),
            "values": {k: v for k, v in sorted(node.values.items())},
        }
        if node.note:
            entry["note"] = node.note
        if node.title:
            entry["title"] = node.title
        out.append(entry)
    return out


def install_key(requirement) -> str:
    """The models/weights.py registry key that satisfies this requirement, or "".

    Resolved here rather than in the browser so the canvas never has to re-implement the match:
    the card can offer a real Install button because this key is what /v1/models/install takes.
    An empty key means the registry has no source for it, which the card says plainly.
    """
    if requirement.kind == "skill":
        env = skill_env_by_key(requirement.skill)
        return env.key if env else ""
    package = package_for_requirement(requirement)
    return package.key if package else ""


def document() -> dict:
    templates = []
    for template in load_definitions().values():
        missing = runnable_missing_executor(template)
        templates.append(
            {
                "id": template.id,
                "name": template.name,
                "description": " ".join(template.description.split()),
                "category": template.category,
                "tags": list(template.tags),
                "caveat": template.caveat,
                "prerequisite": template.prerequisite,
                "stages_without_executor": list(missing),
                "models": [
                    {
                        k: v
                        for k, v in sorted(
                            {**m.model_dump(mode="json"), "install_key": install_key(m)}.items()
                        )
                        if v not in ("", False)
                    }
                    for m in template.models
                ],
                "nodes": positioned(template),
                "wires": [w.model_dump(mode="json") for w in template.wires],
                "order": list(template.order),
            }
        )
    return {
        "$comment": (
            "GENERATED by scripts/export_workflows.py from workflows/*.yaml. Tracked on purpose: "
            "this file is the drift gate, because the TS it produces is git-ignored."
        ),
        "schema": "cf.workflow_templates.v1",
        "templates": templates,
    }


def to_ts(doc: dict) -> str:
    body = json.dumps(doc["templates"], indent=2, sort_keys=False)
    return (
        BANNER
        + "\n"
        + "/** Every workflow the catalogue offers, laid out and ready for the canvas.\n"
        + " *\n"
        + " * Deliberately untyped here: the shape is asserted by templates.ts, which is the only\n"
        + " * consumer, so this module stays a pure data file with no imports to keep in step.\n"
        + " */\n"
        + "export const WORKFLOW_TEMPLATE_DATA = "
        + body
        + " as const;\n\n"
        + "export const WORKFLOW_TEMPLATE_IDS = WORKFLOW_TEMPLATE_DATA.map((t) => t.id);\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the generated files are stale")
    args = ap.parse_args()

    doc = document()
    json_text = canonical_dumps(doc) + "\n"
    ts_text = to_ts(doc)

    if args.check:
        stale = []
        if not JSON_OUT.is_file() or JSON_OUT.read_text() != json_text:
            stale.append(str(JSON_OUT.relative_to(REPO_ROOT)))
        if not TS_OUT.is_file() or TS_OUT.read_text() != ts_text:
            stale.append(str(TS_OUT.relative_to(REPO_ROOT)))
        if stale:
            print(json.dumps({"stale": stale, "fix": "uv run python scripts/export_workflows.py"}))
            return 1
        print(json.dumps({"templates": len(doc["templates"]), "stale": []}))
        return 0

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json_text)
    TS_OUT.write_text(ts_text)
    incomplete = [t["id"] for t in doc["templates"] if t["stages_without_executor"]]
    print(
        json.dumps(
            {
                "templates": len(doc["templates"]),
                "json": str(JSON_OUT.relative_to(REPO_ROOT)),
                "ts": str(TS_OUT.relative_to(REPO_ROOT)),
                "with_unrunnable_stages": incomplete,
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
