"""Write docs/explainer-capabilities.md from the contracts: actions x templates and surfaces."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, get_args

from pydantic import BaseModel

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "explainer-capabilities.md"
sys.path.insert(0, str(REPO / "python"))
from content_factory.schemas import explainer as x  # noqa: E402

TEMPLATES: dict[str, type[BaseModel]] = {
    "chart": x.ChartTemplate,
    "diagram": x.DiagramTemplate,
    "text": x.TextTemplate,
    "source_document": x.SourceDocumentTemplate,
}
RENDERED_SINCE = {
    "chart": "Phase 2",
    "diagram": "Phase 2",
    "text": "Phase 2",
    "source_document": "Phase 3",
}


def _field_line(name: str, info: Any) -> str:
    annotation = (
        str(info.annotation)
        .replace("typing.", "")
        .replace("content_factory.schemas.explainer.", "")
    )
    default = "" if info.is_required() else f" = {info.default!r}"
    return f"| `{name}` | `{annotation}`{default} |"


def render() -> str:
    lines = [
        "# Explainer capabilities",
        "",
        "Generated by `scripts/export_explainer_capabilities.py` from `schemas/explainer.py`;",
        "do not edit.",
        "Every template renders at 1920x1080 at 30 fps (`ChannelProfile.episode_format`),",
        "starts from `Scene.initial_visible`, ends in the state its beats leave behind, and",
        "persists that state for the whole scene. Duration is resolved by the compiler from",
        "narration cues plus the reading-time floor; actions in one beat run in index order and",
        "may overlap, beats never reorder. An action outside this table fails validation with the",
        "supported templates named; a `capability_request` is the planner's way to ask for more.",
        "",
        "## Action x template",
        "",
        "| Action | " + " | ".join(TEMPLATES) + " |",
        "|---|" + "---|" * len(TEMPLATES),
    ]
    for action, templates in x.ACTION_TEMPLATES.items():
        cells = ["yes" if t in templates else "—" for t in TEMPLATES]
        lines.append(f"| `{action}` | " + " | ".join(cells) + " |")
    lines += ["", "## Template surfaces", ""]
    for name, model in TEMPLATES.items():
        lines += [
            f"### `{name}` (rendered since {RENDERED_SINCE[name]})",
            "",
            "| Field | Type |",
            "|---|---|",
        ]
        for field_name, info in model.model_fields.items():
            lines.append(_field_line(field_name, info))
        lines.append("")
    variants = get_args(x.TextTemplate.model_fields["variant"].annotation)
    kinds = get_args(x.ChartTemplate.model_fields["chart_kind"].annotation)
    lines += [
        "## Variants",
        "",
        f"- chart kinds: {', '.join(f'`{k}`' for k in kinds)}",
        f"- text variants: {', '.join(f'`{v}`' for v in variants)}",
        "- duration classes: " + ", ".join(f"`{d}`" for d in get_args(x.DurationClass)),
        "- cue relations: " + ", ".join(f"`{r}`" for r in get_args(x.CueRelation)),
        "",
        "## Working examples",
        "",
        "- `episodes/amdahl/` — 8.6 min episode: stacked bars with progressive filters, a line",
        "  chart, a diagram, a formula, lists, big numbers and five source-document scenes.",
        "- `episodes/latency/` — 2.9 min: source documents from three captures, a two-node",
        "  diagram, stacked bars, a formula.",
        "- `episodes/gears/` — 2.8 min: three bar charts from one article's table, five source",
        "  scenes.",
        "- `fixtures/explainer/amdahl/` — stacked bar chart, big number, statement (Gate B1).",
        "- `fixtures/explainer/sixty/` — statement, big number, diagram, bar, line, list, formula",
        "  (Gate C4).",
        "- `fixtures/explainer/render/bundle-min.json` — a compiled bundle the renderer loads by",
        "  default.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is out of date; run scripts/export_explainer_capabilities.py")
            raise SystemExit(1)
        print("capabilities doc up to date")
    else:
        OUT.write_text(text, encoding="utf-8")
        print(OUT.relative_to(REPO))
