"""Generate Python and TS token modules from the yaml block in docs/DESIGN_SYSTEM.md."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[1]
DOC = REPO / "docs" / "DESIGN_SYSTEM.md"
PY_OUT = REPO / "python" / "content_factory" / "explainer" / "tokens_gen.py"
TS_OUT = REPO / "packages" / "explainer-ui" / "src" / "tokens.gen.ts"
PARITY_OUT = REPO / "fixtures" / "explainer" / "tokens-parity.json"

sys.path.insert(0, str(REPO / "python"))
from content_factory.explainer.color import Oklch, hex_of, oklch_to_srgb  # noqa: E402


def load_tokens(doc: Path = DOC) -> dict[str, Any]:
    match = re.search(r"```yaml\n(.*?)```", doc.read_text(encoding="utf-8"), re.S)
    if match is None:
        msg = f"{doc} has no ```yaml block"
        raise SystemExit(msg)
    data = yaml.safe_load(match.group(1))
    if not isinstance(data, dict) or "design_system_version" not in data:
        msg = "the yaml block must be a mapping with design_system_version"
        raise SystemExit(msg)
    return data


def _walk_oklch(node: Any, out: dict[str, list[float]], prefix: str = "") -> None:
    if isinstance(node, dict):
        if "oklch" in node:
            key = node.get("id") or prefix
            out[str(key)] = [float(v) for v in node["oklch"]]
        for k, v in node.items():
            _walk_oklch(v, out, f"{prefix}.{k}" if prefix else str(k))
    elif isinstance(node, list):
        for i, v in enumerate(node):
            _walk_oklch(v, out, f"{prefix}[{i}]")


def parity(tokens: dict[str, Any]) -> dict[str, str]:
    colors: dict[str, list[float]] = {}
    _walk_oklch(tokens["color"], colors)
    return {k: hex_of(oklch_to_srgb(Oklch(*v))) for k, v in sorted(colors.items())}


def write_outputs(tokens: dict[str, Any]) -> None:
    hexes = parity(tokens)
    header = "GENERATED by scripts/gen_design_tokens.py from docs/DESIGN_SYSTEM.md; do not edit."
    py = (
        f'"""{header}"""\n\nfrom __future__ import annotations\n\nfrom typing import Any\n\n'
        f"DESIGN_SYSTEM_VERSION = {int(tokens['design_system_version'])}\n"
        f"TOKENS: dict[str, Any] = {tokens!r}\n"
        f"SRGB_HEX: dict[str, str] = {hexes!r}\n"
    )
    PY_OUT.write_text(py, encoding="utf-8")
    subprocess.run(["uv", "run", "ruff", "format", str(PY_OUT)], check=True, capture_output=True)
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    ts = (
        f"// {header}\n"
        f"export const DESIGN_SYSTEM_VERSION = {int(tokens['design_system_version'])} as const;\n"
        f"export const TOKENS = {json.dumps(tokens, indent=2, ensure_ascii=False)} as const;\n"
    )
    TS_OUT.write_text(ts, encoding="utf-8")
    PARITY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PARITY_OUT.write_text(json.dumps(hexes, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    write_outputs(load_tokens())
    print(json.dumps({"py": str(PY_OUT.relative_to(REPO)), "ts": str(TS_OUT.relative_to(REPO))}))
